from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PYTHON = ROOT / ".venv" / "Scripts" / "python.exe"
PHASE_TEMPLATE_MODEL = ROOT / "outputs" / "trajectory_phase_template_bc" / "trajectory_phase_template_bc_20260720_160007.npz"
TRAJECTORY_PRIOR_RESIDUAL_MODEL = ROOT / "outputs" / "trajectory_prior_residual_bc" / "trajectory_prior_residual_bc_v1_candidate_20260721_040050.npz"
TIMING_AWARE_TRAJECTORY_PRIOR_RESIDUAL_MODEL = ROOT / "outputs" / "timing_aware_trajectory_prior_residual_bc" / "timing_aware_trajectory_prior_residual_bc_v1_candidate_20260721_070442.npz"
TRAJECTORY_CHUNK_MODEL = ROOT / "outputs" / "chunk_bc" / "trajectory_chunk_bc_20260720_043500.npz"
TRAJECTORY_KNN_MODEL = ROOT / "outputs" / "trajectory_knn_bc" / "trajectory_knn_chunk_bc_20260720_053423.npz"
CONTACT_AWARE_TRAJECTORY_KNN_MODEL = ROOT / "outputs" / "trajectory_knn_bc" / "contact_aware_trajectory_knn_20260720_233445.npz"
TORCH_ACT_MODEL = ROOT / "outputs" / "torch_act" / "torch_act_state_chunk_20260720_055409.pt"
PHASE_WEIGHTED_TORCH_ACT_MODEL = ROOT / "outputs" / "torch_act" / "phase_weighted_torch_act_v1_candidate_20260720_225108.pt"
CONTACT_PHASE_GATED_TORCH_ACT_MODEL = ROOT / "outputs" / "torch_act" / "contact_phase_gated_torch_act_v1_candidate_20260721_003304.pt"
CONTACT_AWARE_PHASE_GATED_TORCH_ACT_MODEL = ROOT / "outputs" / "torch_act" / "contact_aware_phase_gated_torch_act_v1_candidate_20260721_004944.pt"
CONTACT_STAGE_DEMO_TORCH_ACT_MODEL = ROOT / "outputs" / "torch_act" / "contact_stage_demo_torch_act_v1_candidate_20260721_014152.pt"
CONTACT_STAGE_PHASE_ACTION_HEAD_MODEL = ROOT / "outputs" / "phase_action_head" / "contact_stage_phase_action_head_v1_candidate_20260721_020941.npz"
CONTACT_HOLD_WEIGHTED_TORCH_ACT_MODEL = ROOT / "outputs" / "torch_act" / "contact_hold_weighted_torch_act_v1_candidate_20260721_023759.pt"
PREFERENCE_MODEL = ROOT / "outputs" / "preference_post_training" / "preference_trajectory_post_training_20260720_165005.npz"
PREFERENCE_RANKED_OBJECTIVE_MODEL = ROOT / "outputs" / "preference_post_training" / "preference_trajectory_post_training_v1_ranked_objective_candidate_20260721_073626.npz"
PREFERENCE_RANKED_FAST_MODEL = ROOT / "outputs" / "preference_post_training" / "preference_trajectory_post_training_v1_ranked_fast_candidate_20260721_075041.npz"
PREFERENCE_TCP_LIFT_RANK_MODEL = ROOT / "outputs" / "preference_post_training" / "preference_trajectory_post_training_v1_tcp_lift_rank_candidate_20260721_090438.npz"
PREFERENCE_CONTACT_AWARE_MODEL = ROOT / "outputs" / "preference_post_training" / "preference_contact_aware_trajectory_post_training_20260721_000449.npz"
PREFERENCE_RANKED_MODEL = ROOT / "outputs" / "preference_post_training" / "preference_ranked_trajectory_post_training_20260721_031024.npz"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a Chinese index for candidate diagnostic rollout videos.")
    parser.add_argument("--videos", type=Path, default=ROOT / "outputs" / "videos")
    parser.add_argument("--output-md", type=Path, default=ROOT / "docs" / "candidate_diagnostic_video_index.md")
    parser.add_argument("--output-csv", type=Path, default=ROOT / "docs" / "candidate_diagnostic_video_index.csv")
    return parser.parse_args()


def q(path: Path) -> str:
    return f'"{path}"'


def ps_command(script: str | Path, args: list[str | Path]) -> str:
    parts = ["&", q(PYTHON), q(ROOT / script)]
    for arg in args:
        parts.append(q(arg) if isinstance(arg, Path) else str(arg))
    return " ".join(parts)


def torch_ps_command(script: str | Path, args: list[str | Path]) -> str:
    return '$env:VLA_TORCH_PACKAGE_DIR="D:\\vla_torch_cuda_pkgs"\n' + ps_command(script, args)


SPECS = [
    {
        "version": "trajectory_phase_template_bc_v1_candidate",
        "video": "trajectory_phase_template_bc_v1_candidate_seed1.mp4",
        "report": "docs/trajectory_phase_template_bc_report.md",
        "method": "显式 phase 模板 / trajectory-conditioned BC 候选",
        "conclusion": "该 seed 的放置指标成功，但 grasp_success=False、物体高度未抬升，说明它更像模板碰撞/推放，不是可靠抓取策略。",
        "boundary": "只能作为 ACT/trajectory-conditioned 路线负例，不能写成可靠 ACT baseline。",
        "viewer": ps_command(
            "scripts/run_trajectory_phase_template_policy.py",
            [
                "--model",
                PHASE_TEMPLATE_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "1",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "800",
                "--gripper-force",
                "140",
                "--friction",
                "3.0",
                "--action-alpha",
                "0.35",
                "--max-arm-delta",
                "0.018",
                "--max-gripper-delta",
                "0.0008",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "trajectory_phase_template_bc",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "1",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "grasp_gated_trajectory_conditioned_chunk_bc_v1_candidate",
        "video": "grasp_gated_trajectory_conditioned_chunk_bc_v1_candidate_seed0.mp4",
        "report": "docs/grasp_gated_trajectory_act_report.md",
        "method": "抓取门控 trajectory-conditioned chunk BC 候选",
        "conclusion": "该 seed 的放置指标成功，但 grasp_success=False、ever_grasp_success=False；慢速动作和夹爪门控仍没有形成真实抓取/抬升。",
        "boundary": "只能作为 trajectory-conditioned chunk BC 控制层诊断负例，不能写成已稳定抓取。",
        "viewer": ps_command(
            "scripts/run_chunk_policy.py",
            [
                "--model",
                TRAJECTORY_CHUNK_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--grasp-gate",
                "--close-phase",
                "0.22",
                "--release-phase",
                "0.78",
                "--near-threshold",
                "0.11",
                "--release-distance",
                "0.095",
                "--open-gripper",
                "0.037",
                "--close-gripper",
                "0.015",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--gripper-kp",
                "900.0",
                "--gripper-force",
                "180.0",
                "--friction",
                "3.0",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_gated_trajectory_chunk_bc",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900.0",
                "--gripper-force",
                "180.0",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "trajectory_prior_residual_bc_v1_candidate",
        "video": "trajectory_prior_residual_bc_v1_candidate_seed0.mp4",
        "report": "docs/trajectory_prior_residual_bc_report.md",
        "method": "分阶段轨迹先验 + residual BC action head 候选",
        "conclusion": "该 seed 放置成功且 tcp_grasp_lift_success=True，但 grasp_success=False、strict_grasp_lift_success=False；说明结构化接触阶段先验改善闭环放置和 TCP 抬升，但仍不能写成严格抓取成功。",
        "boundary": "只能作为 trajectory-conditioned BC / ACT 路线的结构化先验诊断候选，不能写成纯 BC、完整官方 ACT、OpenVLA/OFT 或真实 WidowX 结果。",
        "viewer": ps_command(
            "scripts/run_trajectory_prior_residual_policy.py",
            [
                "--model",
                TRAJECTORY_PRIOR_RESIDUAL_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--residual-scale",
                "0.25",
                "--action-alpha",
                "1.0",
                "--max-arm-delta",
                "0.02",
                "--max-gripper-delta",
                "0.0008",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "trajectory_prior_residual_bc",
                "--version",
                "trajectory_prior_residual_bc_v1_candidate",
                "--model",
                TRAJECTORY_PRIOR_RESIDUAL_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--action-alpha",
                "1.0",
                "--max-arm-delta",
                "0.02",
                "--max-gripper-delta",
                "0.0008",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "timing_aware_trajectory_prior_residual_bc_v1_candidate",
        "video": "timing_aware_trajectory_prior_residual_bc_v1_candidate_seed0.mp4",
        "report": "docs/timing_aware_trajectory_prior_residual_bc_report.md",
        "method": "时序感知分阶段轨迹先验 + residual BC action head 候选",
        "conclusion": "最终参数 residual-scale=0.02 下 seed0 放置成功且 tcp_grasp_lift_success=True，但 grasp_success=False、strict_grasp_lift_success=False；5+5 评测显示 train-range 5/5、held-out 4/5，说明强时序先验和很小 residual 可恢复放置与 TCP 抬升，但严格抓取仍未解决。",
        "boundary": "只能作为 trajectory-conditioned BC / ACT 路线的时序先验诊断候选，不能写成完整官方 ACT、OpenVLA/OFT、稳定严格抓取或真实 WidowX 结果。",
        "viewer": ps_command(
            "scripts/run_timing_aware_trajectory_prior_residual_policy.py",
            [
                "--model",
                TIMING_AWARE_TRAJECTORY_PRIOR_RESIDUAL_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "3500",
                "--viewer",
                "--duration",
                "90",
                "--speed",
                "0.05",
                "--residual-scale",
                "0.02",
                "--action-alpha",
                "1.0",
                "--max-arm-delta",
                "0.02",
                "--max-gripper-delta",
                "0.0008",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "timing_aware_trajectory_prior_residual_bc",
                "--version",
                "timing_aware_trajectory_prior_residual_bc_v1_candidate",
                "--model",
                TIMING_AWARE_TRAJECTORY_PRIOR_RESIDUAL_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "3500",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--residual-scale",
                "0.02",
                "--action-alpha",
                "1.0",
                "--max-arm-delta",
                "0.02",
                "--max-gripper-delta",
                "0.0008",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "preference_trajectory_post_training_v1_candidate",
        "video": "preference_trajectory_post_training_v1_candidate_seed0.mp4",
        "report": "docs/preference_trajectory_post_training_report.md",
        "method": "偏好加权 trajectory-kNN 后训练候选",
        "conclusion": "该 seed 的放置指标成功，但 grasp_success=False；偏好权重改善了训练范围目标距离，却没有形成真实抓取/抬升。",
        "boundary": "只能作为 trajectory-level preference/reward-weighted 后训练负例，不能写成在线 RL 或真实偏好优化成功。",
        "viewer": ps_command(
            "scripts/run_preference_trajectory_post_training_policy.py",
            [
                "--model",
                PREFERENCE_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--preference-power",
                "1.0",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "800",
                "--gripper-force",
                "140",
                "--friction",
                "3.0",
                "--action-alpha",
                "0.25",
                "--max-arm-delta",
                "0.012",
                "--max-gripper-delta",
                "0.0005",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "preference_trajectory_post_training",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "preference_trajectory_post_training_v1_ranked_objective_candidate",
        "video": "preference_trajectory_post_training_v1_ranked_objective_candidate_seed0.mp4",
        "report": "docs/preference_trajectory_post_training_v1_ranked_objective_summary.md",
        "method": "episode-ranked preference trajectory-kNN dense objective 候选",
        "conclusion": "sample-stride=8 的 ranked objective 让 train-range 放置达到 4/5，但 held-out 0/5；固定 seed0 视频 success=False、tcp_grasp_lift_success=False、grasp_success=False，说明它仍没有解决真实抓取或泛化。",
        "boundary": "只能写成离线 trajectory-level ranking/preference weighting 负例，不能升级为正式 preference_trajectory_post_training_v1、在线 RL、真实偏好优化或 VLA 后训练。",
        "viewer": ps_command(
            "scripts/run_preference_trajectory_post_training_policy.py",
            [
                "--model",
                PREFERENCE_RANKED_OBJECTIVE_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--preference-power",
                "1.0",
                "--action-alpha",
                "0.85",
                "--max-arm-delta",
                "0.04",
                "--max-gripper-delta",
                "0.0015",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "preference_trajectory_post_training",
                "--version",
                "preference_trajectory_post_training_v1_ranked_objective_candidate",
                "--model",
                PREFERENCE_RANKED_OBJECTIVE_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "800",
                "--gripper-force",
                "140",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "preference_trajectory_post_training_v1_ranked_fast_candidate",
        "video": "preference_trajectory_post_training_v1_ranked_fast_candidate_seed0.mp4",
        "report": "docs/preference_trajectory_post_training_v1_ranked_fast_summary.md",
        "method": "episode-ranked preference trajectory-kNN 快速后训练候选",
        "conclusion": "ranked preference objective 的来源更清楚，train-range 放置 2/5、held-out 0/5；seed0 有放置和 TCP 抬升轨迹，但 grasp_success=False、strict_grasp_lift_success=False。",
        "boundary": "只能写成离线 trajectory-level ranking/preference weighting 负例，不能升级为正式 preference_trajectory_post_training_v1、在线 RL、真实偏好优化或 VLA 后训练。",
        "viewer": ps_command(
            "scripts/run_preference_trajectory_post_training_policy.py",
            [
                "--model",
                PREFERENCE_RANKED_FAST_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--preference-power",
                "1.0",
                "--action-alpha",
                "0.85",
                "--max-arm-delta",
                "0.04",
                "--max-gripper-delta",
                "0.0015",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "preference_trajectory_post_training",
                "--version",
                "preference_trajectory_post_training_v1_ranked_fast_candidate",
                "--model",
                PREFERENCE_RANKED_FAST_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "800",
                "--gripper-force",
                "140",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "preference_trajectory_post_training_v1_tcp_lift_rank_candidate",
        "video": "preference_trajectory_post_training_v1_tcp_lift_rank_candidate_seed0.mp4",
        "report": "docs/preference_trajectory_post_training_v1_tcp_lift_rank_report.md",
        "method": "TCP 抬升排序偏好 trajectory-kNN 后训练候选",
        "conclusion": "tcp-lift preference objective 让 train-range 放置 5/5 且 TCP 抬升 5/5；但 grasp_success=False、strict_grasp_lift_success=False，held-out 只有 1/5 放置且 TCP 抬升 0/5。",
        "boundary": "只能写成离线 placed/tcp-lift ranking preference weighting 负例，不能升级为正式 preference_trajectory_post_training_v1、在线 RL、真实偏好优化或 VLA 后训练。",
        "viewer": ps_command(
            "scripts/run_preference_trajectory_post_training_policy.py",
            [
                "--model",
                PREFERENCE_TCP_LIFT_RANK_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--preference-power",
                "1.0",
                "--action-alpha",
                "0.85",
                "--max-arm-delta",
                "0.04",
                "--max-gripper-delta",
                "0.0015",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "preference_trajectory_post_training",
                "--version",
                "preference_trajectory_post_training_v1_tcp_lift_rank_candidate",
                "--model",
                PREFERENCE_TCP_LIFT_RANK_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "800",
                "--gripper-force",
                "140",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "grasp_gated_torch_act_state_chunk_v1_candidate",
        "video": "grasp_gated_torch_act_state_chunk_v1_candidate_seed0.mp4",
        "report": "docs/grasp_gated_trajectory_act_report.md",
        "method": "抓取门控 Torch ACT state chunk 候选",
        "conclusion": "该 seed 放置失败，且 grasp_success=False、ever_grasp_success=False；保守门控没有解决 ACT 接触保持和抬升失败。",
        "boundary": "只能作为 Torch ACT 控制层诊断负例，不能写成 ACT 已稳定抓取。",
        "viewer": torch_ps_command(
            "scripts/run_torch_act_policy.py",
            [
                "--model",
                TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--grasp-gate",
                "--close-phase",
                "0.22",
                "--release-phase",
                "0.78",
                "--near-threshold",
                "0.11",
                "--release-distance",
                "0.095",
                "--open-gripper",
                "0.037",
                "--close-gripper",
                "0.015",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--replan-interval",
                "4",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--gripper-kp",
                "900.0",
                "--gripper-force",
                "180.0",
                "--friction",
                "3.0",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": torch_ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_gated_torch_act",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900.0",
                "--gripper-force",
                "180.0",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "phase_weighted_torch_act_v1_candidate",
        "video": "phase_weighted_torch_act_v1_candidate_seed0.mp4",
        "report": "docs/phase_weighted_torch_act_report.md",
        "method": "阶段加权 Torch ACT 候选",
        "conclusion": "该 seed 放置失败，grasp_success=False、ever_grasp_success=False；阶段加权降低离线误差，但没有形成稳定接触、夹紧和抬升。",
        "boundary": "只能作为阶段加权 ACT 训练诊断负例，不能写成完整 ACT 或稳定抓取成功。",
        "viewer": torch_ps_command(
            "scripts/run_torch_act_policy.py",
            [
                "--model",
                PHASE_WEIGHTED_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.02",
                "--action-alpha",
                "0.25",
                "--max-arm-delta",
                "0.012",
                "--max-gripper-delta",
                "0.0005",
                "--replan-interval",
                "4",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": torch_ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "phase_weighted_torch_act",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "contact_phase_gated_torch_act_v1_candidate",
        "video": "contact_phase_gated_torch_act_v1_candidate_seed0.mp4",
        "report": "docs/contact_phase_gated_torch_act_report.md",
        "method": "接触/阶段门控 Torch ACT 候选",
        "conclusion": "该 seed 放置失败，tcp_grasp_lift_success=False，strict_grasp_lift_success=False；5+5 评测显示放置 0/10，仅 held-out seed101 出现一次 TCP 抬升诊断，说明 phase-one-hot、grasp/lift 加权和 grasp gate 仍不能稳定解决 ACT 接触保持。",
        "boundary": "只能作为 Torch ACT-style 接触/阶段诊断负例，不能写成完整官方 ACT、稳定抓取成功、OpenVLA/OFT 或真实 WidowX 结果。",
        "viewer": ps_command(
            "scripts/run_torch_act_policy.py",
            [
                "--model",
                CONTACT_PHASE_GATED_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--grasp-gate",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--replan-interval",
                "4",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_gated_torch_act",
                "--version",
                "contact_phase_gated_torch_act_v1_candidate",
                "--model",
                CONTACT_PHASE_GATED_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "contact_aware_phase_gated_torch_act_v1_candidate",
        "video": "contact_aware_phase_gated_torch_act_v1_candidate_seed0.mp4",
        "report": "docs/contact_aware_phase_gated_torch_act_report.md",
        "method": "相对几何 + 阶段门控 Torch ACT 候选",
        "conclusion": "seed0 放置失败，tcp_grasp_lift_success=False，strict_grasp_lift_success=False；10 次评测为放置 0/10、TCP 抓取抬升 0/10、标准 ever_grasp_success 0/10。相对几何特征降低了离线误差，但没有转化成闭环抓取能力。",
        "boundary": "只能写成 trajectory-conditioned / ACT-style 相对几何消融负例，不能写成完整官方 ACT、稳定抓取成功、OpenVLA/OFT 或真实 WidowX 结果。",
        "viewer": ps_command(
            "scripts/run_torch_act_policy.py",
            [
                "--model",
                CONTACT_AWARE_PHASE_GATED_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--grasp-gate",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--replan-interval",
                "4",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_gated_torch_act",
                "--version",
                "contact_aware_phase_gated_torch_act_v1_candidate",
                "--model",
                CONTACT_AWARE_PHASE_GATED_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "grasp_lift_subpolicy_probe_v1_candidate",
        "video": "grasp_lift_subpolicy_probe_v1_candidate_seed0.mp4",
        "report": "docs/grasp_lift_subpolicy_probe_report.md",
        "method": "scripted expert / IK 抓取抬升上界诊断",
        "conclusion": "该 seed 放置成功，grasp_success=False，但 max_object_z 达标且 tcp_grasp_lift_success=True；说明环境与控制上界可完成抓放流程，同时标准 grasp 指标仍需单独报告。",
        "boundary": "只能作为 scripted expert / IK 控制上界和指标口径诊断，不能写成 learned BC/ACT/VLA baseline 成功，也不能替代真实 WidowX 验证。",
        "viewer": ps_command(
            "scripts/run_expert.py",
            [
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--min-success-rate",
                "0",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.02",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "800",
                "--gripper-force",
                "140",
                "--friction",
                "3.0",
                "--approach-z",
                "0.12",
                "--grasp-z",
                "0.008",
                "--lift-z",
                "0.18",
                "--retries",
                "2",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_lift_subpolicy_probe",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "contact_stage_subpolicy_v1_candidate",
        "video": "contact_stage_subpolicy_v1_candidate_seed0.mp4",
        "report": "docs/contact_stage_subpolicy_report.md",
        "method": "分阶段 contact-stage scripted subpolicy 上界诊断",
        "conclusion": "seed0 放置成功，tcp_grasp_lift_success=True，stage trace 记录 approach/descend/close/lift/transfer/place/release/retreat/hold；10 次评测 train-range 5/5、held-out 5/5，但标准 strict_grasp_lift_success=0/10。",
        "boundary": "只能写成 scripted subpolicy / contact-stage 上界诊断，不能写成 BC、ACT、Diffusion Policy、VLA 或真实 WidowX 学习策略成功。",
        "viewer": ps_command(
            "scripts/run_contact_stage_subpolicy.py",
            [
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--retries",
                "2",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "contact_stage_subpolicy",
                "--version",
                "contact_stage_subpolicy_v1_candidate",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "contact_stage_demo_torch_act_v1_candidate",
        "video": "contact_stage_demo_torch_act_v1_candidate_seed0.mp4",
        "report": "docs/contact_stage_demo_torch_act_report.md",
        "method": "Contact-stage 成功示范训练的 Torch ACT 候选",
        "conclusion": "seed0 放置失败，grasp_success=False，max_object_z=0.0447；10 次评测 train-range 0/5、held-out 0/5、tcp_grasp_lift_success=0/10、strict_grasp_lift_success=0/10。说明即使用 contact-stage 成功示范，当前 state-only ACT-style 仍未学出稳定接触控制。",
        "boundary": "只能写成更干净 scripted 示范训练 ACT 的候选诊断，不能写成完整官方 ACT、稳定抓取或 VLA 后训练成功。",
        "viewer": ps_command(
            "scripts/run_torch_act_policy.py",
            [
                "--model",
                CONTACT_STAGE_DEMO_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--grasp-gate",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--replan-interval",
                "4",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_gated_torch_act",
                "--version",
                "contact_stage_demo_torch_act_v1_candidate",
                "--model",
                CONTACT_STAGE_DEMO_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "grasp_gated_trajectory_knn_v1_candidate",
        "video": "grasp_gated_trajectory_knn_v1_candidate_seed0.mp4",
        "report": "docs/grasp_gated_trajectory_knn_report.md",
        "method": "夹爪门控 trajectory-kNN 候选",
        "conclusion": "该 seed 的放置指标成功，但 grasp_success=False；门控确实闭合过夹爪，却没有形成抬升抓取。",
        "boundary": "只能作为夹爪门控消融负例，不能写成 trajectory-kNN 已解决真实 grasp。",
        "viewer": ps_command(
            "scripts/run_grasp_gated_trajectory_knn_policy.py",
            [
                "--model",
                TRAJECTORY_KNN_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--arm-kp",
                "150",
                "--arm-force",
                "100",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--action-alpha",
                "0.25",
                "--max-arm-delta",
                "0.012",
                "--max-gripper-delta",
                "0.0005",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_gated_trajectory_knn",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "contact_stage_phase_action_head_v1_candidate",
        "video": "contact_stage_phase_action_head_v1_candidate_seed101.mp4",
        "report": "docs/contact_stage_phase_action_head_report.md",
        "method": "Contact-stage 成功示范训练的 phase action-head 候选",
        "conclusion": "seed101 原始放置 success=True，但 grasp_success=False、tcp_grasp_lift_success=False、strict_grasp_lift_success=False；10 次评测 train-range 放置 0/5、held-out 放置 1/5、TCP 抬升 0/10、严格抓取 0/10。说明显式阶段 action-head 可偶然把目标距离推近，但仍没有学会稳定抓取/抬升。",
        "boundary": "只能写成 contact-stage 成功示范训练的轻量 phase action-head 候选诊断，不能写成稳定抓取、真实 VLA 后训练、OpenVLA LoRA 或完整 ACT 成功。",
        "viewer": ps_command(
            "scripts/run_phase_action_head.py",
            [
                "--model",
                CONTACT_STAGE_PHASE_ACTION_HEAD_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "101",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--phase-mode",
                "progress",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "phase_action_head",
                "--version",
                "contact_stage_phase_action_head_v1_candidate",
                "--model",
                CONTACT_STAGE_PHASE_ACTION_HEAD_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "101",
                "--steps",
                "2840",
                "--phase-mode",
                "progress",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "contact_hold_weighted_torch_act_v1_candidate",
        "video": "contact_hold_weighted_torch_act_v1_candidate_seed0.mp4",
        "report": "docs/contact_hold_weighted_torch_act_report.md",
        "method": "Contact-stage 成功示范 + 接触保持加权 Torch ACT 候选",
        "conclusion": "seed0 放置失败，grasp_success=False、strict_grasp_lift_success=False，但 tcp_grasp_lift_success=True、max_object_z=0.0882；10 次评测 train-range 放置 0/5、held-out 放置 0/5。说明接触保持加权带来一次局部 TCP 抬升迹象，但仍没有形成稳定抓取和放置。",
        "boundary": "只能写成 contact-hold loss 加权的 ACT 候选诊断，不能写成完整官方 ACT、稳定抓取、稳定 learned grasp、真实 VLA 后训练或真实 WidowX 成功。",
        "viewer": ps_command(
            "scripts/run_torch_act_policy.py",
            [
                "--model",
                CONTACT_HOLD_WEIGHTED_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--grasp-gate",
                "--action-alpha",
                "0.12",
                "--max-arm-delta",
                "0.006",
                "--max-gripper-delta",
                "0.00025",
                "--replan-interval",
                "4",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "grasp_gated_torch_act",
                "--version",
                "contact_hold_weighted_torch_act_v1_candidate",
                "--model",
                CONTACT_HOLD_WEIGHTED_TORCH_ACT_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "contact_aware_trajectory_knn_v1_candidate",
        "video": "contact_aware_trajectory_knn_v1_candidate_seed0.mp4",
        "report": "docs/contact_aware_trajectory_knn_report.md",
        "method": "相对几何增强 / contact-aware trajectory-kNN 候选",
        "conclusion": "该 seed 放置成功且 tcp_grasp_lift_success=True，但标准 grasp_success=False；5+5 评测显示 train-range 5/5、held-out 1/5，说明相对几何增强改善训练范围复现，尚未解决留出泛化和稳定抓取。",
        "boundary": "只能作为相对几何特征消融候选，不能写成可靠 learned grasp、完整 ACT 或真实 VLA 后训练成功。",
        "viewer": ps_command(
            "scripts/run_trajectory_knn_policy.py",
            [
                "--model",
                CONTACT_AWARE_TRAJECTORY_KNN_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--action-alpha",
                "0.25",
                "--max-arm-delta",
                "0.012",
                "--max-gripper-delta",
                "0.0005",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "contact_aware_trajectory_knn",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "gripper_timing_contact_probe_v1_candidate",
        "video": "gripper_timing_contact_probe_v1_candidate_seed0.mp4",
        "report": "docs/gripper_timing_contact_probe_report.md",
        "method": "夹爪闭合时序 / 接触保持 scripted diagnostic probe",
        "conclusion": "tight_close_hold 固定视频 success=True、tcp_grasp_lift_success=True、max_object_z=0.1727，但 ever_standard_grasp_success=False、strict_grasp_lift_success=False；说明闭合后保持能维持 TCP 抬升和放置，但标准严格抓取口径仍未触发。",
        "boundary": "只能作为 contact/gripper timing 候选诊断，不能写成 learned BC、ACT、Diffusion Policy、VLA、OpenVLA 后训练或真实 WidowX 成功。",
        "viewer": ps_command(
            "scripts/run_gripper_timing_probe.py",
            [
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--variant",
                "tight_close_hold",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "gripper_timing_contact_probe",
                "--version",
                "gripper_timing_contact_probe_v1_candidate",
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "3560",
                "--variant",
                "tight_close_hold",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--gripper-kp",
                "900",
                "--gripper-force",
                "180",
                "--friction",
                "3.0",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "preference_contact_aware_trajectory_post_training_v1_candidate",
        "video": "preference_contact_aware_trajectory_post_training_v1_candidate_seed0.mp4",
        "report": "docs/preference_contact_aware_trajectory_post_training_report.md",
        "method": "偏好加权 + 相对几何 trajectory-conditioned BC 后训练候选",
        "conclusion": "该 seed 放置成功且 tcp_grasp_lift_success=True，但标准 grasp_success=False；5+5 评测显示 train-range 5/5、held-out 1/5，held-out tcp_grasp_lift_success=0/5，说明偏好权重和相对几何组合仍主要记忆训练分布，不能证明稳定抓取泛化。",
        "boundary": "只能作为 trajectory-level preference weighting 与 relative-geometry 特征叠加的本地诊断候选，不能写成在线 RL、真实人类偏好优化、完整 ACT、OpenVLA/OFT 或真实 WidowX 结果。",
        "viewer": ps_command(
            "scripts/run_preference_trajectory_post_training_policy.py",
            [
                "--model",
                PREFERENCE_CONTACT_AWARE_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "2840",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--preference-power",
                "1.0",
                "--action-alpha",
                "0.25",
                "--max-arm-delta",
                "0.012",
                "--max-gripper-delta",
                "0.0005",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "preference_trajectory_post_training",
                "--version",
                "preference_contact_aware_trajectory_post_training_v1_candidate",
                "--model",
                PREFERENCE_CONTACT_AWARE_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "2840",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--log-every",
                "0",
            ],
        ),
    },
    {
        "version": "preference_ranked_trajectory_post_training_v1_candidate",
        "video": "preference_ranked_trajectory_post_training_v1_candidate_seed0.mp4",
        "report": "docs/preference_ranked_trajectory_post_training_report.md",
        "method": "episode 内排序偏好 + 相对几何 trajectory-kNN 后训练候选",
        "conclusion": "快速 2+2 诊断中 train-range 放置 2/2、held-out 放置 1/2；seed0 固定视频 success=True、tcp_grasp_lift_success=True、max_object_z=0.1732，但标准 grasp_success=False、strict_grasp_lift_success=False，说明排序偏好能复现目标距离和局部抬升迹象，仍不能证明稳定抓取。",
        "boundary": "只能写成 ranked preference trajectory 后训练候选诊断；不能写成在线 RL、真实人类偏好优化、完整 ACT、OpenVLA/Robot VLA 后训练或真实 WidowX 成功。",
        "viewer": ps_command(
            "scripts/run_preference_trajectory_post_training_policy.py",
            [
                "--model",
                PREFERENCE_RANKED_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--episodes",
                "1",
                "--steps",
                "1800",
                "--viewer",
                "--duration",
                "60",
                "--speed",
                "0.05",
                "--k",
                "3",
                "--phase-window",
                "0.03",
                "--min-candidates",
                "256",
                "--history-decay",
                "0.25",
                "--preference-power",
                "1.2",
                "--action-alpha",
                "0.22",
                "--max-arm-delta",
                "0.010",
                "--max-gripper-delta",
                "0.00045",
                "--replan-interval",
                "1",
                "--temporal-ensemble",
                "--ensemble-decay",
                "0.1",
                "--stop-on-unsafe",
                "--log-every",
                "500",
            ],
        ),
        "export": ps_command(
            "scripts/export_video.py",
            [
                "--method",
                "preference_trajectory_post_training",
                "--version",
                "preference_ranked_trajectory_post_training_v1_candidate",
                "--model",
                PREFERENCE_RANKED_MODEL,
                "--task",
                "place_blue_cube_blue_pad",
                "--complexity",
                "medium",
                "--seed",
                "0",
                "--steps",
                "1800",
                "--camera",
                "top_rgb",
                "--fps",
                "24",
                "--frame-stride",
                "12",
                "--width",
                "640",
                "--height",
                "480",
                "--action-alpha",
                "0.22",
                "--max-arm-delta",
                "0.010",
                "--max-gripper-delta",
                "0.00045",
                "--log-every",
                "0",
            ],
        ),
    },
]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def rel(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def build_rows(args: argparse.Namespace) -> list[dict[str, str]]:
    rows = []
    for spec in SPECS:
        video = args.videos / spec["video"]
        metadata = read_json(video.with_suffix(".json"))
        summary = metadata["summary"]
        tcp_lift = summary.get("tcp_grasp_lift_success")
        result = f"success={summary['success']}, grasp_success={summary['grasp_success']}"
        if tcp_lift is not None:
            result += f", tcp_grasp_lift_success={tcp_lift}"
        rows.append(
            {
                "版本": spec["version"],
                "方法定位": spec["method"],
                "seed": str(metadata["seed"]),
                "结果": result,
                "目标距离": f"{float(summary['target_distance']):.4f}",
                "物体高度": f"{float(summary['object_z']):.4f}",
                "出界": str(summary["out_of_table"]),
                "视频文件": rel(video),
                "元数据文件": rel(video.with_suffix(".json")),
                "报告文件": spec["report"],
                "实验结论": spec["conclusion"],
                "论文边界": spec["boundary"],
                "完整viewer命令": spec["viewer"],
                "重新导出视频命令": spec["export"],
            }
        )
    return rows


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def md_row(values: list[str]) -> str:
    escaped = [value.replace("|", "\\|").replace("\n", " ") for value in values]
    return "| " + " | ".join(escaped) + " |"


def write_md(path: Path, rows: list[dict[str, str]]) -> None:
    lines = [
        "# 候选方法诊断视频索引",
        "",
        "版本：`candidate_diagnostic_video_index_v1`",
        "",
        "用途：集中记录 trajectory-conditioned BC / ACT / post-training 路线中的候选负例视频证据。它们用于解释为什么当前实现不能登记为可靠 ACT 或真实偏好后训练 baseline，量化结论仍以对应 CSV/JSON 评测为准。",
        "",
        "## 1. 视频明细",
        "",
        md_row(["版本", "方法定位", "seed", "结果", "目标距离", "物体高度", "视频文件", "论文边界"]),
        md_row(["---", "---", "---:", "---", "---:", "---:", "---", "---"]),
    ]
    for row in rows:
        lines.append(
            md_row(
                [
                    f"`{row['版本']}`",
                    row["方法定位"],
                    row["seed"],
                    row["结果"],
                    row["目标距离"],
                    row["物体高度"],
                    f"`{row['视频文件']}`",
                    row["论文边界"],
                ]
            )
        )

    lines.extend(["", "## 2. 完整可视化命令", ""])
    for row in rows:
        lines.extend([f"### {row['版本']}", "", "```powershell", row["完整viewer命令"], "```", ""])

    lines.extend(["## 3. 重新导出视频命令", ""])
    for row in rows:
        lines.extend([f"### {row['版本']}", "", "```powershell", row["重新导出视频命令"], "```", ""])

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows = build_rows(args)
    write_csv(args.output_csv, rows)
    write_md(args.output_md, rows)
    print(f"candidate_video_md: {args.output_md}", flush=True)
    print(f"candidate_video_csv: {args.output_csv}", flush=True)
    print(f"candidate_video_rows: {len(rows)}", flush=True)


if __name__ == "__main__":
    main()
